
ALTER PROCEDURE [dbo].[OBTENERSEGMENTOTERCEROS]
@IDCCOSTO INT,
@IDUNEGOCIO INT
AS
BEGIN
SELECT s.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO  FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON CU.ID = SC.ID_CCOSTO
INNER JOIN SEGMENTO S ON SC.ID_SEGMENTO = S.ID
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID_CCOSTO=@IDCCOSTO AND CU.ID_UNEGOCIO=@IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Servicios'
END;

ALTER PROCEDURE [dbo].[OBTENERSEGMENTOSCONSULTORES]
@IDCCOSTO INT,
@IDUNEGOCIO INT
AS
BEGIN
SELECT S.NOMBRE,C.CUENTA,C.IDCUENTA,s.ID AS IDSEGMENTO FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID_CCOSTO=@IDCCOSTO AND CU.ID_UNEGOCIO=@IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Costos' 
END;




use PROYECTO_CONTROL_HORAS



ALTER TABLE PLANILLA_USUSARIO_PROYECTO
ADD OBSERVACIONES VARCHAR(200)

ALTER TABLE PLANILLA_USUSARIO_PROYECTO
ADD FECHA_REGISTRO DATE NOT NULL


ALTER TABLE PLANILLA
DROP COLUMN FECHA 



ALTER TABLE  PLANILLA_USUSARIO_PROYECTO
DROP CONSTRAINT [ID_PLANILLA_FK]

ALTER TABLE PLANILLA
ADD ID_USUARIO INT NOT NULL


ALTER TABLE PLANILLA
ADD CONSTRAINT ID_USUARIO_FK FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)


ALTER TABLE PLANILLA_USUSARIO_PROYECTO
ADD ID_PLANILLA INT NOT NULL

ALTER TABLE PLANILLA_USUSARIO_PROYECTO
ADD CONSTRAINT ID_PLANILLA_FK FOREIGN KEY(ID_PLANILLA) REFERENCES PLANILLA(ID)



ALTER PROCEDURE [dbo].[HH_USUARIO_PROYECTO]
@IDUSUARIO INT,
@IDPROYECTO INT
AS
BEGIN
    -- Declaración de variables
    DECLARE @RECURSO VARCHAR(100);
    DECLARE @TIPO_CONSULTOR VARCHAR(200);

    -- Obtener el recurso y el tipo de consultor
    SELECT 
        @RECURSO = R.NOMBRE_RECURSO,
        @TIPO_CONSULTOR = R.TIPO_CONSULTOR
    FROM USUARIO_PROYECTO UP
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO AND UP.ID_PROYECTO = @IDPROYECTO;

    -- Selección de horas asignadas según el tipo de recurso
    SELECT 
		UP.ID AS 'IDUSUARIOPROYCTO',
        UP.ID_USUARIO AS 'ID_USUARIO',
        R.NOMBRE_RECURSO AS 'RECURSO',
        U.NOMBRE AS 'NOMBRE_USUARIO',
        UP.ID_PROYECTO AS 'ID_PROYECTO',
        CASE 
            WHEN @RECURSO = 'Socio' THEN UP.HH_SOCIOS
            WHEN @RECURSO = 'Staff' THEN UP.HH_STAFF
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor A' THEN UP.HH_CONSULTORA
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor B' THEN UP.HH_CONSULTORB
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor C' THEN UP.HH_CONSULTORC
            ELSE 0 -- Si no coincide, asigna 0 horas
        END AS 'HHASIGNADAS',
        R.TIPO_CONSULTOR AS 'TIPO_CONSULTOR'
    FROM USUARIO_PROYECTO UP
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO AND UP.ID_PROYECTO = @IDPROYECTO;
END;