



ALTER TABLE FACTURA
ADD IDSEGMENTO INT NOT NULL


ALTER TABLE FACTURA
ADD CONSTRAINT IDSEGFAC FOREIGN KEY(IDSEGMENTO) REFERENCES SEGMENTO(ID)



ALTER TABLE USUARIO_PROYECTO
DROP COLUMN IDCUENTA


ALTER TABLE USUARIO_PROYECTO 
ADD IDSEGMENTO INT 


ALTER TABLE USUARIO_PROYECTO 
ADD CONSTRAINT IDUSUSEG FOREIGN KEY(IDSEGMENTO) REFERENCES SEGMENTO(ID)


ALTER TABLE PROYECTO_SERVICIO
DROP COLUMN IDCUENTA

ALTER TABLE PROYECTO_SERVICIO
ADD IDSEGMENTO INT

ALTER TABLE PROYECTO_SERVICIO
ADD CONSTRAINT IDSERSEG FOREIGN KEY(IDSEGMENTO) REFERENCES SEGMENTO(ID)



ALTER TABLE PROYECTO_GASTOS 
DROP COLUMN IDCUENTA

ALTER TABLE PROYECTO_GASTOS
ADD IDSEGMENTO INT


ALTER TABLE PROYECTO_GASTOS
ADD CONSTRAINT IDGASEG FOREIGN KEY (IDSEGMENTO) REFERENCES SEGMENTO(ID)



ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,
@HHCONSULTORB INT,
@HHCONSULTORC INT,
@IDSEGMENTOSOCIO INT,
@IDSEGMENTOSTAFF INT,
@IDSEGMENTOCONSULTORA INT,
@IDSEGMENTOCONSULTORB INT,
@IDSEGMENTOCONSULTORC INT,
@IDSEGMENTOFACTURA INT,
@ID_PROYECTO INT OUTPUT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 
 DECLARE @MONTOIVA DECIMAL(10,2) = 0;
 IF(@AFECTAIVA = 'si')
 BEGIN
 SET @MONTOIVA = @MONTO * 0.19;
 END;
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA,MONTOIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA,@MONTOIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)




SET @ID_PROYECTO = SCOPE_IDENTITY();

INSERT INTO FACTURA (ID_PROYECTO,IDSEGMENTO) VALUES (@ID_PROYECTO,@IDSEGMENTOFACTURA)


IF(@HHSOCIOS>0)
BEGIN
DECLARE @COSTOUNITARIO DECIMAL(10,2)
SELECT @COSTOUNITARIO=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Socio'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; -- Primer consultor (A)

SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY; -- Segundo consultor (B)

SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; -- Tercer consultor (C)

-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2)
SELECT @COSTOUNITARIOCONSULTORA=COSTO_UNITARIO FROM  
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; 

 
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA,CostoUnitarioAsignado,IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA,@COSTOUNITARIOCONSULTORA,@IDSEGMENTOCONSULTORA);
END;

IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
SELECT  @COSTOUNITARIOCONSULTORB=COSTO_UNITARIO
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB,CostoUnitarioAsignado,IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB,@COSTOUNITARIOCONSULTORB,@IDSEGMENTOCONSULTORB);
END;

IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
SELECT @COSTOUNITARIOCONSULTORC=COSTO_UNITARIO
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; 
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC,CostoUnitarioAsignado,IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC,@COSTOUNITARIOCONSULTORC,@IDSEGMENTOCONSULTORC);
END;


ALTER PROCEDURE [dbo].[OBTENERSEGMENTOHONORARIOS]
@IDCCOSTOCODIGO INT,
@IDRECURSO INT
AS
BEGIN
DECLARE @ROL_RECURSO VARCHAR(200);
SELECT @ROL_RECURSO=R.NOMBRE_RECURSO FROM USUARIO U INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO WHERE U.ID_RECURSO = @IDRECURSO

IF(@ROL_RECURSO='Consultor Externo')
BEGIN
SELECT S.NOMBRE,C.CUENTA,C.IDCUENTA,s.ID AS IDSEGMENTO  FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCCOSTOCODIGO AND S.TIPO_SEGMENTO = 'Honorarios' AND S.NOMBRE LIKE '%Consultor%'
END
ELSE
BEGIN
IF(@ROL_RECURSO='Profesional')
begin
SELECT S.NOMBRE,C.CUENTA,C.IDCUENTA,s.ID AS IDSEGMENTO  FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCCOSTOCODIGO AND S.TIPO_SEGMENTO = 'Honorarios' AND S.NOMBRE LIKE '%Profesional%'
end
END
END;




ALTER PROCEDURE [dbo].[FILTRARSEGMENTOGASTOS]
@IDCOSDIGOCOSTO INT,
@NOMBRESEGMENTO VARCHAR(200)
AS
BEGIN

IF (@NOMBRESEGMENTO = 'Pasajes')
BEGIN
SELECT S.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCOSDIGOCOSTO AND S.TIPO_SEGMENTO = 'Gastos' AND S.NOMBRE LIKE '%Movilización%' 
END
ELSE
BEGIN
SELECT S.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCOSDIGOCOSTO AND S.TIPO_SEGMENTO = 'Gastos' AND S.NOMBRE LIKE '%Otros%' 
END
END;



ALTER PROCEDURE [dbo].[GENERARTABLASEGMENTOFACTURA]
@IDCCOSTO INT,
@IDUNEGOCIO INT
AS
BEGIN
SELECT S.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO   FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON SC.ID_SEGMENTO = S.ID
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID_CCOSTO=@IDCCOSTO AND CU.ID_UNEGOCIO=@IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Factura' 
END;



ALTER PROCEDURE [dbo].[OBTENERSEGMENTOTERCEROS]
@IDCCOSTOCODIGO INT
AS
BEGIN
SELECT s.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO  FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON CU.ID = SC.ID_CCOSTO
INNER JOIN SEGMENTO S ON SC.ID_SEGMENTO = S.ID
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCCOSTOCODIGO AND S.NOMBRE LIKE '%Costos%' 
END;


ALTER PROCEDURE [dbo].[OBTENERSEGMENTOSCONSULTORES]
@IDCODIGOCCOSTO INT
AS
BEGIN
SELECT S.NOMBRE,C.CUENTA,C.IDCUENTA,s.ID AS IDSEGMENTO FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID = @IDCODIGOCCOSTO AND S.TIPO_SEGMENTO = 'Costos' AND S.NOMBRE LIKE '%Consultor%'
END;