CREATE PROCEDURE CONSULTA_HH_USUARIOS
    @IDUSUARIO INT
AS
BEGIN
    -- Declaración de variables
    DECLARE @RECURSO VARCHAR(100);
    DECLARE @TIPO_CONSULTOR VARCHAR(200);

    -- Obtener el recurso y el tipo de consultor
    SELECT 
        @RECURSO = R.NOMBRE_RECURSO,
        @TIPO_CONSULTOR = R.TIPO_CONSULTOR
    FROM USUARIO_PROYECTO UP
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO;

    -- Selección de horas asignadas y sumatoria total
    SELECT 
        SUM(CASE 
                WHEN @RECURSO = 'Socio' THEN UP.HH_SOCIOS
                WHEN @RECURSO = 'Staff' THEN UP.HH_STAFF
				WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor A' THEN UP.HH_CONSULTORA
				WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor B' THEN UP.HH_CONSULTORB
				WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor C' THEN UP.HH_CONSULTORC
                ELSE 0 -- Si no coincide, asigna 0 horas
            END) AS 'HHASIGNADAS',
			R.HH_ANUALES as HHANUALES
    FROM PROYECTO P
    INNER JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO 
      AND P.STATUS_PROYECTO = 2 
      AND GETDATE() BETWEEN P.FECHA_INICIO AND P.FECHA_TERMINO
	GROUP BY R.HH_ANUALES; 
END;