

ALTER PROCEDURE HH_USUARIO_PROYECTOS_TOTAL
@IDUSUARIO INT

AS
BEGIN
    -- Declaración de variables
    DECLARE @RECURSO VARCHAR(100);
    DECLARE @TIPO_CONSULTOR VARCHAR(200);

    -- Obtener el recurso y el tipo de consultor
    SELECT 
        @RECURSO = R.NOMBRE_RECURSO,
        @TIPO_CONSULTOR = R.TIPO_CONSULTOR
    FROM USUARIO_PROYECTO UP
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO;

    -- Selección de horas asignadas según el tipo de recurso
    SELECT DISTINCT
		UP.ID AS 'IDUSUARIOPROYCTO',
        UP.ID_USUARIO AS 'ID_USUARIO',
        R.NOMBRE_RECURSO AS 'RECURSO',
        U.NOMBRE AS 'NOMBRE_USUARIO',
        UP.ID_PROYECTO AS 'ID_PROYECTO',
		P.NOMBRE AS 'NOMBREPROYECTO',
        CASE 
            WHEN @RECURSO = 'Socio' THEN UP.HH_SOCIOS
            WHEN @RECURSO = 'Staff' THEN UP.HH_STAFF
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor A' THEN UP.HH_CONSULTORA
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor B' THEN UP.HH_CONSULTORB
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor C' THEN UP.HH_CONSULTORC
            ELSE 0 -- Si no coincide, asigna 0 horas
        END AS 'HHASIGNADAS',
        R.TIPO_CONSULTOR AS 'TIPO_CONSULTOR'
    FROM PROYECTO P
	INNER JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
	
    WHERE UP.ID_USUARIO = @IDUSUARIO AND  P.STATUS_PROYECTO=2
	;
END;



