CREATE TABLE [dbo].[TOTAL_RECURSOS]
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_RECURSO VARCHAR(100) NOT NULL,  -- Puede ser 'Socio' o 'Staff'
    TOTAL_HH_ANUALES DECIMAL(10, 2) NOT NULL DEFAULT 0  -- Total de horas anuales iniciales
);


ALTER PROCEDURE [dbo].[INGRESAR_USUARIO]
@NOMBRE VARCHAR(200),
@NOMBRE_USUARIO VARCHAR(200),
@CONTRASENA NVARCHAR(MAX),
@TELEFONO VARCHAR(20),
@EMAIL VARCHAR(90),
@ID_ROL INT,
@NOMBRE_RECURSO VARCHAR(200),
@NUMERO_HORAS_SEMANALES INT,
@COSTO_UNITARIO DECIMAL(10,2),
@PORCENTAJEHORAS FLOAT,
@FECHAINICIO DATE,
@FECHAFIN DATE
AS
BEGIN
DECLARE @IDRECURSO INT;
DECLARE @HHMENSUALES DECIMAL(10,2);
DECLARE @HHANUALES DECIMAL(10,2);
SET @HHANUALES = dbo.CALCULARHHANUALES(@NUMERO_HORAS_SEMANALES, @PORCENTAJEHORAS);
SET @HHMENSUALES =  dbo.CALCULARHHMENSUALES(@NUMERO_HORAS_SEMANALES, @PORCENTAJEHORAS);
INSERT INTO RECURSO (NOMBRE_RECURSO,NUMERO_HORAS,COSTO_UNITARIO,PROCENTAJE_PROYECTO,HH_MENSUALES,DESDE,HASTA,HH_ANUALES) VALUES (@NOMBRE_RECURSO,@NUMERO_HORAS_SEMANALES,@COSTO_UNITARIO,@PORCENTAJEHORAS,@HHMENSUALES,@FECHAINICIO,@FECHAFIN,@HHANUALES)

SET @IDRECURSO = SCOPE_IDENTITY();


INSERT INTO USUARIO(NOMBRE,NOMBRE_USUARIO,CONTRASENA,TELEFONO,EMAIL,ID_ROL,ID_RECURSO) VALUES(@NOMBRE,@NOMBRE_USUARIO,@CONTRASENA,@TELEFONO,@EMAIL,@ID_ROL,@IDRECURSO)


   IF @NOMBRE_RECURSO = 'Socio'
    BEGIN
        UPDATE TOTAL_HORAS_ANUALES
        SET TOTAL_HH_ANUALES = TOTAL_HH_ANUALES + @HHANUALES
        WHERE TIPO_RECURSO = 'Socio';
    END
    ELSE IF @NOMBRE_RECURSO = 'Staff'
    BEGIN
        UPDATE TOTAL_HORAS_ANUALES
        SET TOTAL_HH_ANUALES = TOTAL_HH_ANUALES + @HHANUALES
        WHERE TIPO_RECURSO = 'Staff';
    END
END;



CREATE PROCEDURE [dbo].[HH_USUARIO_PROYECTOS_GANTT]
@IDUSUARIO INT

AS
BEGIN
    -- Declaración de variables
    DECLARE @RECURSO VARCHAR(100);
    DECLARE @TIPO_CONSULTOR VARCHAR(200);

    -- Obtener el recurso y el tipo de consultor
    SELECT 
        @RECURSO = R.NOMBRE_RECURSO,
        @TIPO_CONSULTOR = R.TIPO_CONSULTOR
    FROM USUARIO_PROYECTO UP
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE UP.ID_USUARIO = @IDUSUARIO;

    -- Selección de horas asignadas según el tipo de recurso
    SELECT DISTINCT
		UP.ID AS 'IDUSUARIOPROYCTO',
        UP.ID_USUARIO AS 'ID_USUARIO',
        R.NOMBRE_RECURSO AS 'RECURSO',
        U.NOMBRE AS 'NOMBRE_USUARIO',
        UP.ID_PROYECTO AS 'ID_PROYECTO',
		P.NOMBRE AS 'NOMBREPROYECTO',
        CASE 
            WHEN @RECURSO = 'Socio' THEN HU.HH_SOCIOS
            WHEN @RECURSO = 'Staff' THEN HU.HH_STAFF
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor A' THEN HU.HH_CONSULTORA
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor B' THEN HU.HH_CONSULTORB
            WHEN @RECURSO = 'Consultor Externo' AND @TIPO_CONSULTOR = 'Consultor C' THEN HU.HH_CONSULTORC
            ELSE 0 -- Si no coincide, asigna 0 horas
        END AS 'HHASIGNADAS',
        R.TIPO_CONSULTOR AS 'TIPO_CONSULTOR'
    FROM PROYECTO P
	INNER JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
	INNER JOIN HH_USUARIO_HISTORIAL HU ON HU.ID_PROYECTO = P.ID
    WHERE UP.ID_USUARIO = @IDUSUARIO AND  P.STATUS_PROYECTO=2 AND GETDATE() BETWEEN P.FECHA_INICIO AND P.FECHA_TERMINO
	;
END;