
USE PROYECTO_CONTROL_HORAS

ALTER TABLE PLANILLA
ADD MES int NOT NULL

ALTER TABLE PLANILLA 
ADD ANIO INT NOT NULL



ALTER procedure [dbo].[INICIOSESION]
@CORREO NVARCHAR(100)
AS
BEGIN

SET NOCOUNT ON;
DECLARE @ID INT,
            @CONTRASEÑA NVARCHAR(255),  
            @NOMBRE NVARCHAR(100),
			@IDROL INT,
			@RECURSO VARCHAR(100);     

    SELECT @ID = U.id,
           @CONTRASEÑA = CONTRASENA,
           @NOMBRE = nombre,
		   @IDROL = ID_ROL,
		   @RECURSO = R.NOMBRE_RECURSO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID= U.ID_RECURSO
    WHERE NOMBRE_USUARIO = @CORREO;


SELECT
        @ID AS 'ID',
        @CONTRASEÑA AS 'CONTRASEÑA',
        @NOMBRE AS 'NOMBRE',
		@IDROL AS 'ROL',
		@RECURSO AS 'RECURSO';
END;











ALTER PROCEDURE [dbo].[RECUPERARPLANILLAUSUARIO]
@IDUSUARIO INT,
@IDPLANILLA INT
AS
BEGIN


SELECT P.ID AS IDPLANILLA,p.MES,P.ANIO,PU.FECHA_REGISTRO,PRO.NOMBRE AS NOMBREPROYECTO, PRO.NUM_PROYECTO AS NUMPROYECTO,PRO.ID AS IDPROYECTO,A.NOMBRE AS NOMBREACTIVIDAD,PU.REGISTRO_HH_PROYECTO AS HHREGISTRADAS
,PU.OBSERVACIONES

 FROM PLANILLA P
INNER JOIN PLANILLA_USUSARIO_PROYECTO PU ON PU.ID_PLANILLA =P.ID
INNER JOIN USUARIO_PROYECTO UP ON PU.ID_USU_PROY = UP.ID
INNER JOIN PROYECTO PRO ON PRO.ID = UP.ID_PROYECTO
INNER JOIN ACTIVIDADES A ON PU.ID_ACTIVIDAD = A.ID
WHERE (P.ID_USUARIO = @IDUSUARIO OR @IDUSUARIO=0 OR @IDUSUARIO IS NULL) AND (P.ID=@IDPLANILLA OR @IDPLANILLA=0 OR @IDPLANILLA IS NULL)
ORDER BY PU.ID DESC
END;















