
USE PROYECTO_CONTROL_HORAS

ALTER TABLE PROYECTO_SERVICIO
ADD FECHA DATE

ALTER TABLE PROYECTO_GASTOS
ADD FECHA DATE

ALTER PROCEDURE [dbo].[OBTENERSERVICIOSPROYECTO]
@IDPROYECTO INT
AS
BEGIN

SELECT S.ID AS IDSERVICIO,S.NOMBRE AS NOMBRESERVICIO,SE.NOMBRE AS NOMBRSEGMENTO,C.CUENTA  ,C.IDCUENTA,PS.MONTO,PS.FECHA FROM PROYECTO P

INNER JOIN PROYECTO_SERVICIO PS ON P.ID = PS.ID_PROYECTO
INNER JOIN SERVICIOS S ON S.ID = PS.ID_SERVICIO
INNER JOIN SEGMENTO SE ON SE.ID = PS.IDSEGMENTO
INNER JOIN CUENTA C ON C.ID = SE.ID_CUENTA
WHERE P.ID = @IDPROYECTO
END;


ALTER PROCEDURE [dbo].[OBTENERGASTOSPROYECTO]
@IDPROYECTO INT
AS
BEGIN

SELECT G.ID AS IDGASTOS,G.NOMBRE AS NOMBREGASTO,SE.ID AS IDSEGMENTO,SE.NOMBRE AS NOMBRSEGMENTO,C.CUENTA  ,C.IDCUENTA,PG.MONTO,PG.FECHA FROM PROYECTO P

INNER JOIN PROYECTO_GASTOS PG ON P.ID = PG.ID_PROYECTO
INNER JOIN GASTOS G ON G.ID = PG.ID_GASTOS
INNER JOIN SEGMENTO SE ON SE.ID = PG.IDSEGMENTO
INNER JOIN CUENTA C ON C.ID = SE.ID_CUENTA
WHERE P.ID = @IDPROYECTO
END;