ALTER PROCEDURE ObtenerProyectosPorUsuario
    @IDUsuario INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        up.ID_PROYECTO,
        p.Nombre AS Nombre_Proyecto,  -- Suponiendo que hay una columna Nombre en la tabla PROYECTO
        up.ID_USUARIO,
        P.NUM_PROYECTO,
		C.NOMBRE AS NOMBRECLIENTE   -- Suponiendo que hay una columna Nombre en la tabla USUARIO
        
    FROM 
        USUARIO_PROYECTO up
    INNER JOIN 
        PROYECTO p ON up.ID_PROYECTO = p.ID
    INNER JOIN 
        USUARIO u ON up.ID_USUARIO = u.ID
	INNER JOIN SUCURSAL_CLIENTE SC ON SC.ID = P.ID_CLIENTE_SUCURSAL
	INNER JOIN CLIENTE C ON C.ID = SC.ID_CLIENTE
    WHERE 
        p.STATUS_PROYECTO = 2  -- Proyectos en estado 2
        AND up.ID_USUARIO = @IDUsuario  -- Filtrar por ID_USUARIO
        AND (
            up.HH_SOCIOS > 0 OR   -- Condición para horas de socios
            up.HH_STAFF > 0 OR    -- Condición para horas de staff
            up.HH_CONSULTORA > 0 OR  -- Condición para horas de Consultor A
            up.HH_CONSULTORB > 0 OR   -- Condición para horas de Consultor B
            up.HH_CONSULTORC > 0     -- Condición para horas de Consultor C
        )
    ORDER BY 
        up.ID_PROYECTO;  -- Ordenar los resultados por proyecto
END




ALTER PROCEDURE [dbo].[OBTENERPROYECTOS]
    @ID INT,
    @IDCLIENTE INT,
    @NOMBRE VARCHAR(200),
    @ID_TIPOEMPRESA INT,
    @STATUS_PROYECTO INT,
    @NUMPROYECTO VARCHAR(100),
    @IDTIPOLOGIA INT,
    @UNIDADNEGOCIO INT,
    @IDCENTROCOSTO INT,
	@IDUSUARIO INT
AS
BEGIN
    SET NOCOUNT ON;  -- Mejora el rendimiento al evitar el conteo de filas

    SELECT 
        P.ID,
        P.NUM_PROYECTO,
        Un.TIPO_UNEGOCIO,
        Un.ID AS IDUNEGOCIO,
        COSTO.ID AS IDCOSTO,
        COSTO.TIPO_CCOSTO,
        CU.CODIGO,
        C.ID AS IDCLIENTE,
        C.NOMBRE AS NOMBRECLIENTE,
        P.NOMBRE AS NOMBREPROYECTO,
        T.TIPO_TIPOLOGIA,
        T.ID AS IDTIPOLOGIA,
        E.TIPO_EMPRESA,
        E.ID AS IDEMPRESA,
        PR.ID AS IDPRESUPESTO,
        PR.AFECTAIVA,
        PR.MONTO,
        PR.MONEDA,
        ST.TIPO_STATUS,
        ST.ID AS STATUSPROYECTO,
        P.PROBABILIDAD,
        P.PORCENTAJE_PROBABILIDAD,
        P.PLAZO,
        P.FECHA_INICIO,
        P.FECHA_TERMINO,
        P.FECHA_PLAZO_NEG,
        S.ID AS IDDEPARTAMENTO,
        S.NOMBRE AS NOMBREDEPARTAMENTO,
		

        -- Horas para Socios
       /* CASE 
            WHEN P.STATUS_PROYECTO = 2 
            THEN SUM(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.HH_SOCIOS END)
            ELSE MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.HH_SOCIOS END)
        END AS HH_SOCIOS,*/

        -- Horas para Staff
       /* CASE 
            WHEN P.STATUS_PROYECTO = 2 
            THEN SUM(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.HH_STAFF END)
            ELSE MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.HH_STAFF END)
        END AS HH_STAFF,*/

        -- Costo y Horas para Socios
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN HH.HH_SOCIOS END) AS HH_SOCIOS,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN CT.CUENTA END) AS CUENTA_SOCIOS,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN CT.IDCUENTA END) AS IDCUENTA_SOCIOS,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN SE.NOMBRE END) AS SEGMENTO_SOCIOS,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.CostoUnitarioAsignado END) AS COSTO_SOCIO,

        -- Costo y Horas para Staff
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN HH.HH_STAFF END) AS HH_STAFF,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN CT.CUENTA END) AS CUENTA_STAFF,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN CT.IDCUENTA END) AS IDCUENTA_STAFF,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN SE.NOMBRE END) AS SEGMENTO_STAFF,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.CostoUnitarioAsignado END) AS COSTO_STAFF,

       -- Horas y Costo para Consultor A
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN HH.HH_CONSULTORA END) AS HH_CONSULTOR_A,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN CT.CUENTA END) AS CUENTA_CONSULTOR_A,
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN CT.IDCUENTA END) AS IDCUENTA_CONSULTOR_A,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN SE.NOMBRE END) AS SEGMENTO_CONSULTOR_A,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN UP.COSTOCONSULTORA END) AS COSTO_CONSULTORA,
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' THEN R.TIPO_CONSULTOR END) AS TIPO_CONSULTOR,

        -- Horas y Costo para Consultor B
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN HH.HH_CONSULTORB END) AS HH_CONSULTOR_B,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN CT.CUENTA END) AS CUENTA_CONSULTOR_B,
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN CT.IDCUENTA END) AS IDCUENTA_CONSULTOR_B,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN SE.NOMBRE END) AS SEGMENTO_CONSULTOR_B,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN UP.COSTOCONSULTORB END) AS COSTO_CONSULTORB,
		 MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' THEN R.TIPO_CONSULTOR END) AS TIPO_CONSULTOR,

        -- Horas y Costo para Consultor C
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN HH.HH_CONSULTORC END) AS HH_CONSULTOR_C,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN CT.CUENTA END) AS CUENTA_CONSULTOR_C,
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN CT.IDCUENTA END) AS IDCUENTA_CONSULTOR_C,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN SE.NOMBRE END) AS SEGMENTO_CONSULTOR_C,
        MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN UP.COSTOCONSULTORC END) AS COSTO_CONSULTORC,
		MAX(CASE WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' THEN R.TIPO_CONSULTOR END) AS TIPO_CONSULTOR

    FROM PROYECTO P
    INNER JOIN SUCURSAL_CLIENTE SC ON SC.ID = P.ID_CLIENTE_SUCURSAL
    LEFT JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    LEFT JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    LEFT JOIN RECURSO R ON R.ID = U.ID_RECURSO
    LEFT JOIN CLIENTE C ON C.ID = SC.ID_CLIENTE
    LEFT JOIN SUCURSAL S ON S.ID = SC.ID_SUCURSAL
    LEFT JOIN TIPOLOGIA T ON T.ID = P.ID_TIPOLOGIA
    LEFT JOIN EMPRESA E ON E.ID = P.TIPO_EMPRESA
    LEFT JOIN CCOSTO_UNEGOCIO CU ON CU.ID = P.ID_CCOSTO_UNEGOCIO 
    LEFT JOIN CCOSTO COSTO ON COSTO.ID = CU.ID_CCOSTO
    LEFT JOIN UNEGOCIO Un ON Un.ID = CU.ID_UNEGOCIO
    LEFT JOIN PRESUPUESTO PR ON PR.ID = P.ID_PRESUPUESTO
    LEFT JOIN STATUS_PROYECTO ST ON ST.ID = P.STATUS_PROYECTO
    LEFT JOIN SEGMENTO SE ON UP.IDSEGMENTO = SE.ID
    LEFT JOIN CUENTA CT ON CT.ID = SE.ID_CUENTA
	LEFT JOIN HH_USUARIO_HISTORIAL HH ON P.ID = HH.ID_PROYECTO
    WHERE (P.ID = @ID OR @ID = 0 OR @ID IS NULL) 
      AND (C.ID = @IDCLIENTE OR @IDCLIENTE = 0 OR @IDCLIENTE IS NULL) 
      AND (P.NOMBRE = @NOMBRE OR @NOMBRE IS NULL)
      AND (P.TIPO_EMPRESA = @ID_TIPOEMPRESA OR @ID_TIPOEMPRESA = 0 OR @ID_TIPOEMPRESA IS NULL) 
      AND (ST.ID = @STATUS_PROYECTO OR @STATUS_PROYECTO = 0 OR @STATUS_PROYECTO IS NULL)
      AND (P.NUM_PROYECTO = @NUMPROYECTO OR @NUMPROYECTO IS NULL)
      AND (P.ID_TIPOLOGIA = @IDTIPOLOGIA OR @IDTIPOLOGIA = 0 OR @IDTIPOLOGIA IS NULL)
      AND (Un.ID = @UNIDADNEGOCIO OR @UNIDADNEGOCIO = 0 OR @UNIDADNEGOCIO IS NULL)
      AND (COSTO.ID = @IDCENTROCOSTO OR @IDCENTROCOSTO = 0 OR @IDCENTROCOSTO IS NULL)
	  AND (U.ID=@IDUSUARIO OR @IDUSUARIO=0 OR @IDUSUARIO IS NULL)
    
    GROUP BY 
        P.ID, P.NUM_PROYECTO, Un.TIPO_UNEGOCIO, 
        PR.MONTO, PR.MONEDA, COSTO.TIPO_CCOSTO, 
        CU.CODIGO, C.NOMBRE, P.NOMBRE, 
        T.TIPO_TIPOLOGIA, E.TIPO_EMPRESA, 
        PR.AFECTAIVA, ST.TIPO_STATUS, 
        P.PROBABILIDAD, P.PORCENTAJE_PROBABILIDAD, 
        P.PLAZO, P.FECHA_INICIO, 
        P.FECHA_TERMINO, P.FECHA_PLAZO_NEG, 
        Un.ID, COSTO.ID, T.ID, E.ID, ST.ID, C.ID, PR.ID, S.ID, S.NOMBRE,P.STATUS_PROYECTO;
END
ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,
@HHCONSULTORB INT,
@HHCONSULTORC INT,
@IDSEGMENTOSOCIO INT,
@IDSEGMENTOSTAFF INT,
@IDSEGMENTOCONSULTORA INT,
@IDSEGMENTOCONSULTORB INT,
@IDSEGMENTOCONSULTORC INT,
@IDSEGMENTOFACTURA INT,
@ID_PROYECTO INT OUTPUT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 
 DECLARE @MONTOIVA DECIMAL(10,2) = 0;
 IF(@AFECTAIVA = 'si')
 BEGIN
 SET @MONTOIVA = @MONTO * 0.19;
 END;
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA,MONTOIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA,@MONTOIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)




SET @ID_PROYECTO = SCOPE_IDENTITY();

INSERT INTO FACTURA (ID_PROYECTO,IDSEGMENTO) VALUES (@ID_PROYECTO,@IDSEGMENTOFACTURA)


IF(@HHSOCIOS>0)
BEGIN
DECLARE @COSTOUNITARIO DECIMAL(10,2)
SELECT @COSTOUNITARIO=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Socio'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'


SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'


SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND  R.TIPO_CONSULTOR = 'Consultor C'


-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORA = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE U.ID = @ConsultorA; -- Utilizar directamente el ID del usuario (consultor A)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORA, @IDSEGMENTOCONSULTORA);
END;

-- Para Consultor B
IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORB = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorB; -- Utilizar directamente el ID del usuario (consultor B)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORB, @IDSEGMENTOCONSULTORB);
END;

-- Para Consultor C
IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORC = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorC; -- Utilizar directamente el ID del usuario (consultor C)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORC, @IDSEGMENTOCONSULTORC);
END;

DECLARE @IDPROYECTO_USUARIO INT;


INSERT INTO HH_USUARIO_HISTORIAL(ID_PROYECTO,HH_SOCIOS,HH_STAFF,HH_CONSULTORA,HH_CONSULTORB,HH_CONSULTORC) 

VALUES(@ID_PROYECTO,@HHSOCIOS,@HHSTAFF,@HHCONSULTORA,@HHCONSULTORB,@HHCONSULTORC)


END;

ALTER PROCEDURE [dbo].[EDITAR_PROYECTO]
    @IDPROYECTO INT,
    @IDPRESUPUESTO INT,
    @MONTO DECIMAL(10,2),
    @MONEDA VARCHAR(200),
    @AFECTAIVA VARCHAR(10),
    @ID_TIPOLOGIA INT,
    @NOMBRE VARCHAR(MAX),
    @FECHA_INICIO DATE,
    @FECHA_TERMINO DATE,
    @PLAZO INT,
    @TIPO_EMPRESA INT,
    @ID_CCOSTO_UNEGOCIO INT,  
    @STATUS_PROYECTO INT,
    @PROBABILIDAD VARCHAR(200),
    @PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
    @FECHA_PLAZO_NEG DATE,
    @HHSOCIOS INT,
    @HHSTAFF INT,
    @HHCONSULTORA INT,
    @HHCONSULTORB INT,
    @HHCONSULTORC INT,
    @IDSEGMENTOSOCIO INT,
    @IDSEGMENTOSTAFF INT,
    @IDSEGMENTOCONSULTORA INT,
    @IDSEGMENTOCONSULTORB INT,
    @IDSEGMENTOCONSULTORC INT,
    @IDSEGMENTOFACTURA INT
AS
BEGIN
    DECLARE @MONTOIVA DECIMAL(10,2) = 0;
    IF(@AFECTAIVA = 'si')
    BEGIN
        SET @MONTOIVA = @MONTO * 0.19;
    END;

    UPDATE PRESUPUESTO 
    SET MONTO = @MONTO, 
        MONEDA = @MONEDA, 
        AFECTAIVA = @AFECTAIVA, 
        MONTOIVA = @MONTOIVA 
    WHERE ID = @IDPRESUPUESTO;

    UPDATE PROYECTO 
    SET ID_PRESUPUESTO = @IDPRESUPUESTO,
        ID_TIPOLOGIA = @ID_TIPOLOGIA,
        NOMBRE = @NOMBRE,
        FECHA_INICIO = @FECHA_INICIO,
        FECHA_TERMINO = @FECHA_TERMINO,
        PLAZO = @PLAZO,
        TIPO_EMPRESA = @TIPO_EMPRESA,
        ID_CCOSTO_UNEGOCIO = @ID_CCOSTO_UNEGOCIO,
        STATUS_PROYECTO = @STATUS_PROYECTO,
        PROBABILIDAD = @PROBABILIDAD,
        PORCENTAJE_PROBABILIDAD = @PORCENTAJE_PROBABILIDAD,
        FECHA_PLAZO_NEG = @FECHA_PLAZO_NEG 
    WHERE ID = @IDPROYECTO;

    UPDATE FACTURA 
    SET IDSEGMENTO = @IDSEGMENTOFACTURA 
    WHERE ID_PROYECTO = @IDPROYECTO;

    DECLARE @ESTADO INT;
    SELECT @ESTADO = STATUS_PROYECTO FROM PROYECTO WHERE ID = @IDPROYECTO;

    -- Llamada al procedimiento para Socios
    /*EXEC ActualizarUsuarioProyecto @IDPROYECTO, @HHSOCIOS, 'Socio', @IDSEGMENTOSOCIO, @ESTADO;*/

    -- Llamada al procedimiento para Staff
    /*EXEC ActualizarUsuarioProyecto @IDPROYECTO, @HHSTAFF, 'Staff', @IDSEGMENTOSTAFF, @ESTADO;*/

    -- Para Consultores Externos
    DECLARE @ConsultorA INT, @ConsultorB INT, @ConsultorC INT;

    -- Asignar consultores A, B y C
    SELECT @ConsultorA = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';

    SELECT @ConsultorB = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';

    SELECT @ConsultorC = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';

    -- Consultor A
    IF(@HHCONSULTORA <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
    END
    ELSE
    BEGIN
		DECLARE @CONSULTORAID INT;
			SELECT @CONSULTORAID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORA = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';
        END;
		IF(@CONSULTORAID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORAA DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORAA = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorA;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORAA, @IDSEGMENTOCONSULTORA);
			
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORA = @HHCONSULTORA,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORA ELSE UP.COSTOCONSULTORA END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORA
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor B
    IF(@HHCONSULTORB <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORBID INT;
			SELECT @CONSULTORBID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORB = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';
        END;
		IF(@CONSULTORBID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORBB DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORBB = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorB;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORBB, @IDSEGMENTOCONSULTORB);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORB = @HHCONSULTORB,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORB ELSE UP.COSTOCONSULTORB END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORB
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor C
	
	
    IF(@HHCONSULTORC <= 0)
	
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORCID INT;
			SELECT @CONSULTORCID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORC = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';
        END;

		IF(@CONSULTORCID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORCC DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORCC = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorC;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORCC, @IDSEGMENTOCONSULTORC);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORC = @HHCONSULTORC,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORC ELSE UP.COSTOCONSULTORC END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORC
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HH SOCIOS*/
   IF(@HHSOCIOS <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
    END
    ELSE
    BEGIN
			DECLARE @SOCIOID INT;
			SELECT @SOCIOID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Socio'  AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIO DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIO = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Socio' ;
        END;
		IF(@SOCIOID IS NULL)
		BEGIN
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Socio';
			UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_SOCIOS = @HHSOCIOS,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIO ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSOCIO
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HHSTAFF*/
	IF(@HHSTAFF <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
    END
    ELSE
    BEGIN
		DECLARE @STAFFID INT;
			SELECT @STAFFID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Staff'  AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOS DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOS = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Staff' ;
        END;
		IF(@STAFFID IS NULL)
		BEGIN
			DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
			SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Staff';
			UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_STAFF = @HHSTAFF,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOS ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSTAFF
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

END;


CREATE TABLE HH_USUARIO_HISTORIAL(


	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_PROYECTO INT ,
	HH_SOCIOS INT,
	HH_STAFF INT,
	HH_CONSULTORA INT,
	HH_CONSULTORB INT,
	HH_CONSULTORC INT,
	CONSTRAINT ID_PROYECT_FK FOREIGN KEY(ID_PROYECTO) REFERENCES USUARIO_PROYECTO

);



ALTER TABLE HH_USUARIO_HISTORIAL
ADD CONSTRAINT ID_PROYECT_FK FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID)

