



alter PROCEDURE FILTRARSEGMENTOGASTOSEDICION
@IDCOSTO INT,
@IDUNEGOCIO INT,
@NOMBRESEGMENTO VARCHAR(200)
AS
BEGIN

IF (@NOMBRESEGMENTO = 'Pasajes')
BEGIN
SELECT s.ID AS IDSEGMENTO, S.NOMBRE,C.IDCUENTA,C.CUENTA FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN UNEGOCIO U ON CU.ID_UNEGOCIO = U.ID
INNER JOIN CCOSTO CO ON CO.ID = CU.ID_CCOSTO
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CO.ID = @IDCOSTO AND U.ID = @IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Gastos' AND S.NOMBRE LIKE '%Movilización%' 
END
ELSE
BEGIN
SELECT s.ID AS IDSEGMENTO, S.NOMBRE,C.IDCUENTA,C.CUENTA FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN UNEGOCIO U ON CU.ID_UNEGOCIO = U.ID
INNER JOIN CCOSTO CO ON CO.ID = CU.ID_CCOSTO
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CO.ID = @IDCOSTO AND U.ID = @IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Gastos' AND S.NOMBRE LIKE '%Otros%' 
END
END;