alter PROCEDURE sp_GetHorasPorUsuarioPorMes
    @IdUsuario INT
AS
BEGIN
    SELECT 
        p.Nombre AS NombreProyecto,
        u.Nombre AS NombreUsuario,
        YEAR(pup.Fecha_Registro) AS Año,
        MONTH(pup.Fecha_Registro) AS Mes,
        SUM(pup.Registro_Hh_Proyecto) AS TotalHoras,
        p.Fecha_Inicio,
        p.Fecha_Termino
    FROM 
        PLANILLA_USUSARIO_PROYECTO pup
    JOIN 
        Usuario_Proyecto up ON pup.ID_USU_PROY = up.Id
    JOIN 
        Usuario u ON up.Id_Usuario = u.Id
    JOIN 
        Proyecto p ON up.Id_Proyecto = p.Id
    WHERE 
        pup.Fecha_Registro BETWEEN p.Fecha_Inicio AND p.Fecha_Termino
        AND u.Id = @IdUsuario  -- Filtro por IdUsuario
    GROUP BY 
        p.Nombre, u.Nombre, YEAR(pup.Fecha_Registro), MONTH(pup.Fecha_Registro), p.Fecha_Inicio, p.Fecha_Termino
    ORDER BY 
        Año, Mes;
END




ALTER PROCEDURE [dbo].[EDITAR_PROYECTO]
    @IDPROYECTO INT,
    @IDPRESUPUESTO INT,
    @MONTO DECIMAL(10,2),
    @MONEDA VARCHAR(200),
    @AFECTAIVA VARCHAR(10),
    @ID_TIPOLOGIA INT,
    @NOMBRE VARCHAR(MAX),
    @FECHA_INICIO DATE,
    @FECHA_TERMINO DATE,
    @PLAZO INT,
    @TIPO_EMPRESA INT,
    @ID_CCOSTO_UNEGOCIO INT,  
    @STATUS_PROYECTO INT,
    @PROBABILIDAD VARCHAR(200),
    @PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
    @FECHA_PLAZO_NEG DATE,
    @HHSOCIOS INT,
    @HHSTAFF INT,
    @HHCONSULTORA INT,
    @HHCONSULTORB INT,
    @HHCONSULTORC INT,
    @IDSEGMENTOSOCIO INT,
    @IDSEGMENTOSTAFF INT,
    @IDSEGMENTOCONSULTORA INT,
    @IDSEGMENTOCONSULTORB INT,
    @IDSEGMENTOCONSULTORC INT,
    @IDSEGMENTOFACTURA INT
AS
BEGIN
    DECLARE @MONTOIVA DECIMAL(10,2) = 0;
    IF(@AFECTAIVA = 'si')
    BEGIN
        SET @MONTOIVA = @MONTO * 0.19;
    END;

    UPDATE PRESUPUESTO 
    SET MONTO = @MONTO, 
        MONEDA = @MONEDA, 
        AFECTAIVA = @AFECTAIVA, 
        MONTOIVA = @MONTOIVA 
    WHERE ID = @IDPRESUPUESTO;

    UPDATE PROYECTO 
    SET ID_PRESUPUESTO = @IDPRESUPUESTO,
        ID_TIPOLOGIA = @ID_TIPOLOGIA,
        NOMBRE = @NOMBRE,
        FECHA_INICIO = @FECHA_INICIO,
        FECHA_TERMINO = @FECHA_TERMINO,
        PLAZO = @PLAZO,
        TIPO_EMPRESA = @TIPO_EMPRESA,
        ID_CCOSTO_UNEGOCIO = @ID_CCOSTO_UNEGOCIO,
        STATUS_PROYECTO = @STATUS_PROYECTO,
        PROBABILIDAD = @PROBABILIDAD,
        PORCENTAJE_PROBABILIDAD = @PORCENTAJE_PROBABILIDAD,
        FECHA_PLAZO_NEG = @FECHA_PLAZO_NEG 
    WHERE ID = @IDPROYECTO;

    UPDATE FACTURA 
    SET IDSEGMENTO = @IDSEGMENTOFACTURA 
    WHERE ID_PROYECTO = @IDPROYECTO;

    DECLARE @ESTADO INT;
    SELECT @ESTADO = STATUS_PROYECTO FROM PROYECTO WHERE ID = @IDPROYECTO;



    -- Para Consultores Externos
    DECLARE @ConsultorA INT, @ConsultorB INT, @ConsultorC INT;

    -- Asignar consultores A, B y C
    SELECT @ConsultorA = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';

    SELECT @ConsultorB = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';

    SELECT @ConsultorC = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';

    -- Consultor A
    IF(@HHCONSULTORA <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
		DECLARE @CONSULTORAID INT;
			SELECT @CONSULTORAID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORA = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';
        END;
		IF(@CONSULTORAID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORAA DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORAA = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorA;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORAA, @IDSEGMENTOCONSULTORA);
			
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORA = @HHCONSULTORA,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORA ELSE UP.COSTOCONSULTORA END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORA
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor B
    IF(@HHCONSULTORB <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		 UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORBID INT;
			SELECT @CONSULTORBID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORB = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';
        END;
		IF(@CONSULTORBID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORBB DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORBB = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorB;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORBB, @IDSEGMENTOCONSULTORB);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORB = @HHCONSULTORB,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORB ELSE UP.COSTOCONSULTORB END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORB
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor C
	
	
    IF(@HHCONSULTORC <= 0)
	
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORCID INT;
			SELECT @CONSULTORCID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORC = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';
        END;

		IF(@CONSULTORCID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORCC DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORCC = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorC;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORCC, @IDSEGMENTOCONSULTORC);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORC = @HHCONSULTORC,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORC ELSE UP.COSTOCONSULTORC END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORC
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HH SOCIOS*/
   IF(@HHSOCIOS <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @SOCIOID INT;
			SELECT @SOCIOID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Socio'  AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIO DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIO = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Socio' ;
        END;
		IF(@SOCIOID IS NULL)
		BEGIN
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Socio';
			UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_SOCIOS = @HHSOCIOS,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIO ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSOCIO
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HHSTAFF*/
	IF(@HHSTAFF <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
		DECLARE @STAFFID INT;
			SELECT @STAFFID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Staff'  AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOS DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOS = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Staff' ;
        END;
		IF(@STAFFID IS NULL)
		BEGIN
			DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
			SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Staff';
			UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_STAFF = @HHSTAFF,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOS ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSTAFF
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

END;
