

ALTER TABLE CLIENTE
ADD TIPOCLIENTE VARCHAR(300)


ALTER PROCEDURE [dbo].[REGISTRARCLIENTE]
@NOMBRE VARCHAR(200),
@DIRECCION VARCHAR(200),
@CIUDAD VARCHAR(200),
@PAIS VARCHAR(200),
@TELEFONO VARCHAR(20),
@PAG_WEB VARCHAR(200),
@LINKEDIN VARCHAR(200),
@INSTAGRAM VARCHAR(200),
@ID_CLIENTE VARCHAR(200),
@NOMBRE_SUCURSAL VARCHAR(200),
@TIPOCLIENTE VARCHAR(300)
AS
BEGIN
DECLARE @ID_SUCURSAL INT;
DECLARE @IDC INT;
INSERT INTO SUCURSAL(NOMBRE) VALUES(@NOMBRE_SUCURSAL)
SET @ID_SUCURSAL = SCOPE_IDENTITY();
INSERT INTO CLIENTE(NOMBRE,DIRECCION,CIUDAD,PAIS,TELEFONO,PAG_WEB,LINKEDIN,INSTAGRAM,ID_CLIENTE,TIPOCLIENTE) VALUES(@NOMBRE,@DIRECCION,@CIUDAD,@PAIS,@TELEFONO,@PAG_WEB,@LINKEDIN,@INSTAGRAM,@ID_CLIENTE,@TIPOCLIENTE)
SET @IDC = SCOPE_IDENTITY();
INSERT INTO SUCURSAL_CLIENTE(ID_CLIENTE,ID_SUCURSAL) VALUES (@IDC,@ID_SUCURSAL)
END;

ALTER PROCEDURE [dbo].[OBTENERCLIENTESINDEX]
@IDCLIENTES INT
AS
BEGIN
    SELECT 
        C.ID, 
        C.NOMBRE, 
        C.DIRECCION, 
        C.CIUDAD, 
        C.PAIS, 
        C.TELEFONO, 
        C.PAG_WEB AS PAGWEB, 
        C.LINKEDIN, 
        C.INSTAGRAM, 
        C.ID_CLIENTE,
		c.TIPOCLIENTE,
        -- Nombres de las sucursales
        STUFF(
            (SELECT ',' + S.NOMBRE
             FROM SUCURSAL_CLIENTE SC
             INNER JOIN SUCURSAL S ON SC.ID_SUCURSAL = S.ID
             WHERE SC.ID_CLIENTE = C.ID
             FOR XML PATH('')), 1, 1, '') AS SUCURSALES_CLIENTE
    FROM CLIENTE C
    WHERE C.ID = @IDCLIENTES OR @IDCLIENTES = 0 OR @IDCLIENTES IS NULL
    ORDER BY C.NOMBRE;
    
    -- Segunda consulta para devolver los IDs de las sucursales por separado
    SELECT SC.ID_SUCURSAL as SucursalIds
    FROM SUCURSAL_CLIENTE SC
    WHERE SC.ID_CLIENTE = @IDCLIENTES;
END;


ALTER PROCEDURE [dbo].[ACTUALIZARCLIENTE]
@ID INT,
@NOMBRE VARCHAR(200),
@DIRECCION VARCHAR(200),
@CIUDAD VARCHAR(200),
@PAIS VARCHAR(200),
@TELEFONO VARCHAR(20),
@PAG_WEB VARCHAR(200),
@LINKEDIN VARCHAR(200),
@INSTAGRAM VARCHAR(200),
@IDSUCURSAL INT,
@NOMBRESUCURSAL VARCHAR(200),
@TIPOCLIENTE VARCHAR(300)
AS
BEGIN
UPDATE CLIENTE SET NOMBRE=@NOMBRE,DIRECCION=@DIRECCION,CIUDAD=@CIUDAD,PAIS=@PAIS,TELEFONO=@TELEFONO,PAG_WEB=@PAG_WEB,LINKEDIN=@LINKEDIN,INSTAGRAM=@INSTAGRAM,TIPOCLIENTE=@TIPOCLIENTE WHERE ID= @ID
UPDATE SUCURSAL SET NOMBRE=@NOMBRESUCURSAL WHERE ID=@IDSUCURSAL
END;