USE PROYECTO_CONTROL_HORAS


ALTER TABLE USUARIO_PROYECTO
DROP CONSTRAINT [USUARIO_PROYECTO_IDPROYECTO_FK]


ALTER TABLE USUARIO_PROYECTO
DROP CONSTRAINT  [USUARIO_PROYECTO_IDUSUARIO_FK]

ALTER TABLE PLANILLA_USUSARIO_PROYECTO
DROP CONSTRAINT [ID_USU_PRO_FK]

DROP TABLE USUARIO_PROYECTO

CREATE TABLE USUARIO_PROYECTO(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_PROYECTO INT NOT NULL,
ID_USUARIO INT NOT NULL,
HH_SOCIOS INT,
HH_STAFF INT,
HH_CONSULTORA INT,
HH_CONSULTORB INT,
HH_CONSULTORC INT,
CONSTRAINT USUARIO_PRO_FK FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID),
CONSTRAINT PRO_USU_FK FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID)
);
ALTER TABLE USUARIO_PROYECTO
ADD IDCUENTA INT
ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@IDCUENTASOCIO INT,
@HHSTAFF INT,
@IDCUENTASTAFF INT,
@HHCONSULTORA INT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 DECLARE @ID_PROYECTO INT;
  
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)
SET @ID_PROYECTO = SCOPE_IDENTITY();
IF(@HHSOCIOS>0)
BEGIN
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,IDCUENTA)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@IDCUENTASOCIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,IDCUENTA)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@IDCUENTASTAFF
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; -- Primer consultor (A)

SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY; -- Segundo consultor (B)

SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; -- Tercer consultor (C)

-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA);
END;

/*IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB);
END;

IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC);
END;*/
END;