ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,
@HHCONSULTORB INT,
@HHCONSULTORC INT,
@IDSEGMENTOSOCIO INT,
@IDSEGMENTOSTAFF INT,
@IDSEGMENTOCONSULTORA INT,
@IDSEGMENTOCONSULTORB INT,
@IDSEGMENTOCONSULTORC INT,
@IDSEGMENTOFACTURA INT,
@ID_PROYECTO INT OUTPUT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 
 DECLARE @MONTOIVA DECIMAL(10,2) = 0;
 IF(@AFECTAIVA = 'si')
 BEGIN
 SET @MONTOIVA = @MONTO * 0.19;
 END;
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA,MONTOIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA,@MONTOIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)




SET @ID_PROYECTO = SCOPE_IDENTITY();

INSERT INTO FACTURA (ID_PROYECTO,IDSEGMENTO) VALUES (@ID_PROYECTO,@IDSEGMENTOFACTURA)


IF(@HHSOCIOS>0)
BEGIN
DECLARE @COSTOUNITARIO DECIMAL(10,2)
SELECT @COSTOUNITARIO=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Socio'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; -- Primer consultor (A)

SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY; -- Segundo consultor (B)

SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; -- Tercer consultor (C)

-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORA = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE U.ID = @ConsultorA; -- Utilizar directamente el ID del usuario (consultor A)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORA, @IDSEGMENTOCONSULTORA);
END;

-- Para Consultor B
IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORB = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorB; -- Utilizar directamente el ID del usuario (consultor B)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORB, @IDSEGMENTOCONSULTORB);
END;

-- Para Consultor C
IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORC = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorC; -- Utilizar directamente el ID del usuario (consultor C)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORC, @IDSEGMENTOCONSULTORC);
END;



END;





ALTER PROCEDURE [dbo].[OBTENERPROYECTOS]
    @ID INT,
    @IDCLIENTE INT,
    @NOMBRE VARCHAR(200),
    @ID_TIPOEMPRESA INT,
    @STATUS_PROYECTO INT,
    @NUMPROYECTO VARCHAR(100),
    @IDTIPOLOGIA INT,
    @UNIDADNEGOCIO INT,
    @IDCENTROCOSTO INT
AS
BEGIN
    SELECT 
        P.ID,
        P.NUM_PROYECTO,
        Un.TIPO_UNEGOCIO,
        COSTO.TIPO_CCOSTO,
        CU.CODIGO,
        C.NOMBRE AS NOMBRECLIENTE,
        P.NOMBRE AS NOMBREPROYECTO,
        T.TIPO_TIPOLOGIA,
        E.TIPO_EMPRESA,
        PR.AFECTAIVA,
        ST.TIPO_STATUS,
        P.PROBABILIDAD,
        P.PORCENTAJE_PROBABILIDAD,
        P.PLAZO,
        P.FECHA_INICIO,
        P.FECHA_TERMINO,
        P.FECHA_PLAZO_NEG,
        S.NOMBRE AS NOMBREDEPARTAMENTO,

        -- Horas para Socios
        MAX(ISNULL(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.HH_SOCIOS 
            END,0)) AS HHSOCIOS,

        -- Cuenta para Socios
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN CT.CUENTA
            END) AS CUENTA_SOCIOS,

        -- ID de Cuenta para Socios
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN CT.IDCUENTA
            END) AS IDCUENTA_SOCIOS,

			--SEGMENTO SOCIOS--
			MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN SE.NOMBRE
            END) AS SEGMENTO_SOCIOS,

		--COSTO UNITARIO SOCIOS
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.CostoUnitarioAsignado
            END) AS COSTO_SOCIO,

        -- Horas para Staff
        MAX(ISNULL(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.HH_STAFF 
            END,0)) AS HHSTAFF,

        -- Cuenta para Staff
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN CT.CUENTA
            END) AS CUENTA_STAFF,

        -- ID de Cuenta para Staff
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN CT.IDCUENTA
            END) AS IDCUENTA_STAFF,


		--SEGMENTO STAFF--
			MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN SE.NOMBRE
            END) AS SEGMENTO_STAFF,

		--COSTO UNITARIO STAFF
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.CostoUnitarioAsignado
            END) AS COSTO_STAFF,

        -- Horas para Consultor A
        MAX(ISNULL(CASE 
				WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
				THEN UP.HH_CONSULTORA 
				END, 0)) AS HH_CONSULTOR_A,

        -- Cuenta para Consultor A
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
            THEN CT.CUENTA
            END) AS CUENTA_CONSULTOR_A,

        -- ID de Cuenta para Consultor A
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
            THEN CT.IDCUENTA
            END) AS IDCUENTA_CONSULTOR_A,
		--SEGMENTO CONSULTOR A--
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
            THEN SE.NOMBRE
            END) AS SEGMENTO_CONSULTOR_A,

		--COSTO UNITARIO CONSULTOR A
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
			THEN UP.COSTOCONSULTORA
            END) AS COSTO_CONSULTORA,


        -- Horas para Consultor B
        MAX(ISNULL(CASE 
				WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
				THEN UP.HH_CONSULTORA 
				END, 0)) AS HH_CONSULTOR_B,

        -- Cuenta para Consultor B
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
            THEN CT.CUENTA
            END) AS CUENTA_CONSULTOR_B,

        -- ID de Cuenta para Consultor B
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
            THEN CT.IDCUENTA
            END) AS IDCUENTA_CONSULTOR_B,
		--SEGMENTO CONSULTOR B--
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
            THEN SE.NOMBRE
            END) AS SEGMENTO_CONSULTOR_B,

		--COSTO UNITARIO CONSULTOR B
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
			THEN UP.COSTOCONSULTORB
            END) AS COSTO_CONSULTORB,

        -- Horas para Consultor C
        MAX(ISNULL(CASE 
				WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
				THEN UP.HH_CONSULTORA 
				END, 0)) AS HH_CONSULTOR_C,

        -- Cuenta para Consultor C
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
            THEN CT.CUENTA
            END) AS CUENTA_CONSULTOR_C,

        -- ID de Cuenta para Consultor C
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
            THEN CT.IDCUENTA
            END) AS IDCUENTA_CONSULTOR_C,
		--SEGMENTO CONSULTOR A--
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
            THEN SE.NOMBRE
            END) AS SEGMENTO_CONSULTOR_C,
		--COSTO UNITARIO CONSULTOR C
		MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
			THEN UP.COSTOCONSULTORC
            END) AS COSTO_CONSULTORC
    FROM PROYECTO P
    INNER JOIN SUCURSAL_CLIENTE SC ON SC.ID = P.ID_CLIENTE_SUCURSAL
    INNER JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    INNER JOIN CLIENTE C ON C.ID = SC.ID_CLIENTE
    INNER JOIN SUCURSAL S ON S.ID = SC.ID_SUCURSAL
    INNER JOIN TIPOLOGIA T ON T.ID = P.ID_TIPOLOGIA
    INNER JOIN EMPRESA E ON E.ID = P.TIPO_EMPRESA
    INNER JOIN CCOSTO_UNEGOCIO CU ON CU.ID = P.ID_CCOSTO_UNEGOCIO 
    INNER JOIN CCOSTO COSTO ON COSTO.ID = CU.ID_CCOSTO
    INNER JOIN UNEGOCIO Un ON Un.ID = CU.ID_UNEGOCIO
    INNER JOIN PRESUPUESTO PR ON PR.ID = P.ID_PRESUPUESTO
    INNER JOIN STATUS_PROYECTO ST ON ST.ID = P.STATUS_PROYECTO
	INNER JOIN SEGMENTO SE ON UP.IDSEGMENTO = SE.ID
	INNER JOIN CUENTA CT ON CT.ID = SE.ID_CUENTA 
    CROSS APPLY (
         SELECT 
        ROW_NUMBER() OVER (
            PARTITION BY R.NOMBRE_RECURSO, UP.ID_PROYECTO 
            ORDER BY UP.ID_PROYECTO, U.ID
        ) - 1 AS RN
    FROM USUARIO_PROYECTO UP2
    INNER JOIN USUARIO U2 ON UP2.ID_USUARIO = U2.ID
    INNER JOIN RECURSO R2 ON U2.ID_RECURSO = R2.ID
    WHERE R2.NOMBRE_RECURSO = R.NOMBRE_RECURSO
      AND UP2.ID_PROYECTO = UP.ID_PROYECTO
    ) AS CA
    WHERE (P.ID = @ID OR @ID = 0 OR @ID IS NULL) 
        AND (C.ID = @IDCLIENTE OR @IDCLIENTE = 0 OR @IDCLIENTE IS NULL) 
        AND (P.NOMBRE = @NOMBRE OR @NOMBRE IS NULL)
        AND (P.TIPO_EMPRESA = @ID_TIPOEMPRESA OR @ID_TIPOEMPRESA = 0 OR @ID_TIPOEMPRESA IS NULL) 
        AND (ST.ID = @STATUS_PROYECTO OR @STATUS_PROYECTO = 0 OR @STATUS_PROYECTO IS NULL)
        AND (P.NUM_PROYECTO = @NUMPROYECTO OR @NUMPROYECTO IS NULL)
        AND (P.ID_TIPOLOGIA = @IDTIPOLOGIA OR @IDTIPOLOGIA = 0 OR @IDTIPOLOGIA IS NULL)
        AND (U.ID = @UNIDADNEGOCIO OR @UNIDADNEGOCIO = 0 OR @UNIDADNEGOCIO IS NULL)
        AND (COSTO.ID = @IDCENTROCOSTO OR @IDCENTROCOSTO = 0 OR @IDCENTROCOSTO IS NULL)
    GROUP BY 
        P.ID, P.NUM_PROYECTO, Un.TIPO_UNEGOCIO, COSTO.TIPO_CCOSTO, 
        CU.CODIGO, C.NOMBRE, P.NOMBRE, T.TIPO_TIPOLOGIA, 
        E.TIPO_EMPRESA, PR.AFECTAIVA, ST.TIPO_STATUS, 
        P.PROBABILIDAD, P.PORCENTAJE_PROBABILIDAD, P.PLAZO, 
        P.FECHA_INICIO, P.FECHA_TERMINO, P.FECHA_PLAZO_NEG, 
        S.NOMBRE;
END;



USE PROYECTO_CONTROL_HORAS



ALTER TABLE USUARIO_PROYECTO
ADD COSTOCONSULTORA decimal(10,2)

ALTER TABLE USUARIO_PROYECTO
ADD COSTOCONSULTORB decimal(10,2)


ALTER TABLE USUARIO_PROYECTO
ADD COSTOCONSULTORC decimal(10,2)


ALTER TABLE USUARIO_PROYECTO
ALTER COLUMN COSTOCONSULTORA DECIMAL(10,2)

ALTER TABLE USUARIO_PROYECTO
ALTER COLUMN COSTOCONSULTORB DECIMAL(10,2)


ALTER TABLE USUARIO_PROYECTO
ALTER COLUMN COSTOCONSULTORC DECIMAL(10,2)