

CREATE TABLE HISTORIAL_COSTOS (
    ID INT PRIMARY KEY IDENTITY(1,1),
    ID_USUARIO INT,
    CostoUnitario DECIMAL(18, 2),
    FechaInicio DATE,
    FechaFin DATE,
    CONSTRAINT FK_HISTORIAL_COSTOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

USE PROYECTO_CONTROL_HORAS


ALTER TABLE USUARIO_PROYECTO
ADD CostoUnitarioAsignado DECIMAL(18, 2);


USE [PROYECTO_CONTROL_HORAS]
GO
/****** Object:  StoredProcedure [dbo].[CREAR_PROYECTO]    Script Date: 03-10-2024 23:50:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,

@HHCONSULTORB INT,

@HHCONSULTORC INT,

@ID_PROYECTO INT OUTPUT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 
 DECLARE @MONTOIVA DECIMAL(10,2) = 0;
 IF(@AFECTAIVA = 'si')
 BEGIN
 SET @MONTOIVA = @MONTO * 0.19;
 END;
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA,MONTOIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA,@MONTOIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)




SET @ID_PROYECTO = SCOPE_IDENTITY();

INSERT INTO FACTURA (ID_PROYECTO) VALUES (@ID_PROYECTO)


IF(@HHSOCIOS>0)
BEGIN
DECLARE @COSTOUNITARIO DECIMAL(10,2)
SELECT @COSTOUNITARIO=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Socio'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; -- Primer consultor (A)

SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY; -- Segundo consultor (B)

SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; -- Tercer consultor (C)

-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2)
SELECT @COSTOUNITARIOCONSULTORA=COSTO_UNITARIO FROM  
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY; 

 
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA,CostoUnitarioAsignado)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA,@COSTOUNITARIOCONSULTORA);
END;

IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
SELECT  @COSTOUNITARIOCONSULTORB=COSTO_UNITARIO
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY;
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB,CostoUnitarioAsignado)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB,@COSTOUNITARIOCONSULTORB);
END;

IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
SELECT @COSTOUNITARIOCONSULTORC=COSTO_UNITARIO
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo'
ORDER BY 
    U.ID
OFFSET 2 ROWS FETCH NEXT 1 ROWS ONLY; 
    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC,CostoUnitarioAsignado)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC,@COSTOUNITARIOCONSULTORC);
END;



END;







ALTER TABLE FACTURA
DROP COLUMN IDCUENTA


ALTER TABLE PROYECTO_GASTOS
DROP COLUMN IDCUENTA