


CREATE TABLE META_FACTURACIONESQX(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ANIO INT NOT NULL,
	MONTO_Q1 DECIMAL(15,2),
	MONTO_Q2 DECIMAL(15,2),
	MONTO_Q3 DECIMAL(15,2),
	MONTO_Q4 DECIMAL(15,2)
);

CREATE TABLE TOTALQUARTERFACTURAANIO(

	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ANIO INT,
	MONTO DECIMAL(15,2)

);


ALTER PROCEDURE INGRESARFACTURAQX
@ANIO INT ,
@MONTOQ1 DECIMAL(15,2),
@MONTOQ2 DECIMAL(15,2),
@MONTOQ3 DECIMAL(15,2),
@MONTOQ4 DECIMAL(15,2)
AS
BEGIN
DECLARE @TOTALMONTOANUAL DECIMAL(15,2);

SET @TOTALMONTOANUAL = CAST(@MONTOQ1 AS DECIMAL(15,2)) + 
                           CAST(@MONTOQ2 AS DECIMAL(15,2)) + 
                           CAST(@MONTOQ3 AS DECIMAL(15,2)) + 
                           CAST(@MONTOQ4 AS DECIMAL(15,2));

INSERT INTO META_FACTURACIONESQX(ANIO,MONTO_Q1,MONTO_Q2,MONTO_Q3,MONTO_Q4)
VALUES (@ANIO,@MONTOQ1,@MONTOQ2,@MONTOQ3,@MONTOQ4)

            INSERT INTO TOTALQUARTERFACTURAANIO(ANIO, MONTO)
            VALUES (@ANIO,@TOTALMONTOANUAL)


END;

EXEC INGRESARFACTURAQX 2024,82000000,185000000,185000000,185000000

SELECT * FROM META_FACTURACIONESQX

SELECT * FROM TOTALQUARTERFACTURAANIO


CREATE PROCEDURE OBTENERMETAFACTURACIONQX
AS
BEGIN
    SELECT ANIO, 
           MONTO_Q1, 
           MONTO_Q2, 
           MONTO_Q3, 
           MONTO_Q4, 
           (MONTO_Q1 + MONTO_Q2 + MONTO_Q3 + MONTO_Q4) AS TotalMontoQ
    FROM META_FACTURACIONESQX;
END;