


ALTER PROCEDURE [dbo].[OBTENERSEGMENTOTERCEROS]
@IDCCOSTO INT,
@IDUNEGOCIO INT
AS
BEGIN
SELECT s.NOMBRE,C.IDCUENTA,C.CUENTA,S.ID AS IDSEGMENTO  FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON CU.ID = SC.ID_CCOSTO
INNER JOIN SEGMENTO S ON SC.ID_SEGMENTO = S.ID
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID_CCOSTO=@IDCCOSTO AND CU.ID_UNEGOCIO=@IDUNEGOCIO AND S.NOMBRE LIKE '%Costos%' 
END;



ALTER PROCEDURE [dbo].[OBTENERSEGMENTOSCONSULTORES]
@IDCCOSTO INT,
@IDUNEGOCIO INT
AS
BEGIN
SELECT S.NOMBRE,C.CUENTA,C.IDCUENTA,s.ID AS IDSEGMENTO FROM CCOSTO_UNEGOCIO CU
INNER JOIN SEGMENTO_CCOSTO SC ON SC.ID_CCOSTO = CU.ID
INNER JOIN SEGMENTO S ON S.ID = SC.ID_SEGMENTO
INNER JOIN CUENTA C ON C.ID = S.ID_CUENTA
WHERE CU.ID_CCOSTO=@IDCCOSTO AND CU.ID_UNEGOCIO=@IDUNEGOCIO AND S.TIPO_SEGMENTO = 'Costos' AND S.NOMBRE LIKE '%Consultor%'
END;