USE [PROYECTO_CONTROL_HORAS]
GO
/****** Object:  StoredProcedure [dbo].[OBTENERPROYECTOS]    Script Date: 05/10/2024 13:43:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[OBTENERPROYECTOS]
    @ID INT,
    @IDCLIENTE INT,
    @NOMBRE VARCHAR(200),
    @ID_TIPOEMPRESA INT,
    @STATUS_PROYECTO INT,
    @NUMPROYECTO VARCHAR(100),
    @IDTIPOLOGIA INT,
    @UNIDADNEGOCIO INT,
    @IDCENTROCOSTO INT
AS
BEGIN
    SELECT 
        P.ID,
        P.NUM_PROYECTO,
        Un.TIPO_UNEGOCIO,
        COSTO.TIPO_CCOSTO,
        CU.CODIGO,
        C.NOMBRE AS NOMBRECLIENTE,
        P.NOMBRE AS NOMBREPROYECTO,
        T.TIPO_TIPOLOGIA,
        E.TIPO_EMPRESA,
        PR.AFECTAIVA,
        ST.TIPO_STATUS,
        P.PROBABILIDAD,
        P.PORCENTAJE_PROBABILIDAD,
        P.PLAZO,
        P.FECHA_INICIO,
        P.FECHA_TERMINO,
        P.FECHA_PLAZO_NEG,
        S.NOMBRE AS NOMBREDEPARTAMENTO,

        -- Obtener una única hora de un solo socio
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Socio' THEN UP.HH_SOCIOS 
            END) AS HHSOCIOS,

        -- Obtener una única hora de un solo staff
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Staff' THEN UP.HH_STAFF 
            END) AS HHSTAFF,


        -- Obtener horas de Consultor A
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'A' 
            THEN UP.HH_CONSULTORA 
            END) AS HH_CONSULTOR_A,

        -- Obtener horas de Consultor B
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'B' 
            THEN UP.HH_CONSULTORB 
            END) AS HH_CONSULTOR_B,

        -- Obtener horas de Consultor C
        MAX(CASE 
            WHEN R.NOMBRE_RECURSO = 'Consultor Externo' AND CHAR(65 + RN) = 'C' 
            THEN UP.HH_CONSULTORC
            END) AS HH_CONSULTOR_C,

        -- Obtener todos los segmentos
        STUFF((SELECT DISTINCT ', ' + S2.NOMBRE
               FROM SEGMENTO S2
               INNER JOIN USUARIO_PROYECTO UP2 ON UP2.IDSEGMENTO = S2.ID
               WHERE UP2.ID_PROYECTO = P.ID
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS IDSEGMENTOS,



			   STUFF((SELECT DISTINCT ', ' + C.CUENTA
               FROM SEGMENTO S2
               INNER JOIN USUARIO_PROYECTO UP2 ON UP2.IDSEGMENTO = S2.ID
			   INNER JOIN CUENTA C ON C.ID = S2.ID_CUENTA
               WHERE UP2.ID_PROYECTO = P.ID
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS CUENTAS,



			     STUFF((SELECT DISTINCT ', ' +  CAST(C.IDCUENTA AS NVARCHAR(10))
               FROM SEGMENTO S2
               INNER JOIN USUARIO_PROYECTO UP2 ON UP2.IDSEGMENTO = S2.ID
			   INNER JOIN CUENTA C ON C.ID = S2.ID_CUENTA
               WHERE UP2.ID_PROYECTO = P.ID
               FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS IDCUENTA 

    FROM PROYECTO P
    INNER JOIN SUCURSAL_CLIENTE SC ON SC.ID = P.ID_CLIENTE_SUCURSAL
    INNER JOIN USUARIO_PROYECTO UP ON UP.ID_PROYECTO = P.ID
    INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
    INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    INNER JOIN CLIENTE C ON C.ID = SC.ID_CLIENTE
    INNER JOIN SUCURSAL S ON S.ID = SC.ID_SUCURSAL
    INNER JOIN TIPOLOGIA T ON T.ID = P.ID_TIPOLOGIA
    INNER JOIN EMPRESA E ON E.ID = P.TIPO_EMPRESA
    INNER JOIN CCOSTO_UNEGOCIO CU ON CU.ID = P.ID_CCOSTO_UNEGOCIO 
    INNER JOIN CCOSTO COSTO ON COSTO.ID = CU.ID_CCOSTO
    INNER JOIN UNEGOCIO Un ON Un.ID = CU.ID_UNEGOCIO
    INNER JOIN PRESUPUESTO PR ON PR.ID = P.ID_PRESUPUESTO
    INNER JOIN STATUS_PROYECTO ST ON ST.ID = P.STATUS_PROYECTO
    CROSS APPLY (
        SELECT 
            ROW_NUMBER() OVER (PARTITION BY R.NOMBRE_RECURSO ORDER BY U.ID) - 1 AS RN
        FROM RECURSO R2
        WHERE R2.NOMBRE_RECURSO = R.NOMBRE_RECURSO
    ) AS CA
    WHERE (P.ID = @ID OR @ID = 0 OR @ID IS NULL) 
        AND (C.ID = @IDCLIENTE OR @IDCLIENTE = 0 OR @IDCLIENTE IS NULL) 
        AND (P.NOMBRE = @NOMBRE OR @NOMBRE IS NULL)
        AND (P.TIPO_EMPRESA = @ID_TIPOEMPRESA OR @ID_TIPOEMPRESA = 0 OR @ID_TIPOEMPRESA IS NULL) 
        AND (ST.ID = @STATUS_PROYECTO OR @STATUS_PROYECTO = 0 OR @STATUS_PROYECTO IS NULL)
        AND (P.NUM_PROYECTO = @NUMPROYECTO OR @NUMPROYECTO IS NULL)
        AND (P.ID_TIPOLOGIA = @IDTIPOLOGIA OR @IDTIPOLOGIA = 0 OR @IDTIPOLOGIA IS NULL)
        AND (U.ID = @UNIDADNEGOCIO OR @UNIDADNEGOCIO = 0 OR @UNIDADNEGOCIO IS NULL)
        AND (COSTO.ID = @IDCENTROCOSTO OR @IDCENTROCOSTO = 0 OR @IDCENTROCOSTO IS NULL)
    GROUP BY 
        P.ID, P.NUM_PROYECTO, Un.TIPO_UNEGOCIO, COSTO.TIPO_CCOSTO, 
        CU.CODIGO, C.NOMBRE, P.NOMBRE, T.TIPO_TIPOLOGIA, 
        E.TIPO_EMPRESA, PR.AFECTAIVA, ST.TIPO_STATUS, 
        P.PROBABILIDAD, P.PORCENTAJE_PROBABILIDAD, P.PLAZO, 
        P.FECHA_INICIO, P.FECHA_TERMINO, P.FECHA_PLAZO_NEG, 
        S.NOMBRE;
END;
