
CREATE TABLE HISTORIAL_NEGOCIACION(

ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ID_PROYECTO INT,
AFECTAIVA VARCHAR(10),
MONTO DECIMAL (10,2),
PLAZO INT,
FECHA DATE,
FECHAINICIO DATE,
FECHATERMINO DATE,
FECHANEGOCIACION DATE,
PROBABILIDAD VARCHAR(20),
NIVELPROBABILIDAD DECIMAL(10,2),
HHSOCIOS INT,
HHSTAFF INT,
HHCONSULTORA INT,
HHCONSULTORB INT,
HHCONSULTORC INT
);

ALTER TABLE HISTORIAL_NEGOCIACION
ADD CONSTRAINT IDPROYECTONEG FOREIGN KEY(ID_PROYECTO) REFERENCES PROYECTO(ID)

USE PROYECTO_CONTROL_HORAS
ALTER TABLE HISTORIAL_NEGOCIACION
ADD  FECHA DATETIME

CREATE PROCEDURE INSERTARNEGOCIACION
@IDPROYECTO INT,
@AFECTAIVA VARCHAR(10),
@MONTO DECIMAL(10,2),
@PLAZO INT,
@FECHAINICIO DATE,
@FECHATERMINO DATE,
@FECHANEGOCIACION DATE,
@PROBABILIDAD VARCHAR(20),
@NIVELPROBABILIDAD DECIMAL(10,2),
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,
@HHCONSULTORB INT,
@HHCONSULTORC INT
AS
BEGIN

INSERT INTO HISTORIAL_NEGOCIACION(ID_PROYECTO,AFECTAIVA,MONTO,PLAZO,FECHA,FECHAINICIO,FECHATERMINO,FECHANEGOCIACION,PROBABILIDAD,NIVELPROBABILIDAD
,HHSOCIOS,HHSTAFF,HHCONSULTORA,HHCONSULTORB,HHCONSULTORC)
VALUES (@IDPROYECTO,@AFECTAIVA,@MONTO,@PLAZO,GETDATE(),@FECHAINICIO,@FECHATERMINO,@FECHANEGOCIACION,@PROBABILIDAD,@NIVELPROBABILIDAD,@HHSOCIOS
,@HHSTAFF,@HHCONSULTORA,@HHCONSULTORB,@HHCONSULTORC)


END;




USE [PROYECTO_CONTROL_HORAS]
GO
/****** Object:  StoredProcedure [dbo].[CREAR_PROYECTO]    Script Date: 15/10/2024 14:49:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[CREAR_PROYECTO]
@MONTO DECIMAL(10,2),
@MONEDA VARCHAR(200),
@AFECTAIVA VARCHAR(10),
@ID_TIPOLOGIA INT,
@NOMBRE VARCHAR(MAX),
@NUM_PROYECTO VARCHAR(MAX),
@FECHA_INICIO DATE,
@FECHA_TERMINO DATE,
@PLAZO INT,
@TIPO_EMPRESA INT,
@ID_CCOSTO_UNEGOCIO INT,
@ID_CLIENTE_SUCURSAL INT,
@STATUS_PROYECTO INT,
@PROBABILIDAD VARCHAR(200),
@PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
@FECHA_PLAZO_NEG DATE,
@HHSOCIOS INT,
@HHSTAFF INT,
@HHCONSULTORA INT,
@HHCONSULTORB INT,
@HHCONSULTORC INT,
@IDSEGMENTOSOCIO INT,
@IDSEGMENTOSTAFF INT,
@IDSEGMENTOCONSULTORA INT,
@IDSEGMENTOCONSULTORB INT,
@IDSEGMENTOCONSULTORC INT,
@IDSEGMENTOFACTURA INT,
@ID_PROYECTO INT OUTPUT
AS
BEGIN
DECLARE @ID_PRESUPUESTO INT;
 
 DECLARE @MONTOIVA DECIMAL(10,2) = 0;
 IF(@AFECTAIVA = 'si')
 BEGIN
 SET @MONTOIVA = @MONTO * 0.19;
 END;
INSERT INTO PRESUPUESTO (MONTO,MONEDA,AFECTAIVA,MONTOIVA) VALUES (@MONTO,@MONEDA,@AFECTAIVA,@MONTOIVA)

SET @ID_PRESUPUESTO= SCOPE_IDENTITY();

INSERT INTO PROYECTO(ID_PRESUPUESTO,ID_TIPOLOGIA,NOMBRE,NUM_PROYECTO,FECHA,FECHA_INICIO,FECHA_TERMINO,PLAZO,TIPO_EMPRESA,ID_CCOSTO_UNEGOCIO,ID_CLIENTE_SUCURSAL,
STATUS_PROYECTO,PROBABILIDAD,PORCENTAJE_PROBABILIDAD,FECHA_PLAZO_NEG)
VALUES(@ID_PRESUPUESTO,@ID_TIPOLOGIA,@NOMBRE,@NUM_PROYECTO,GETDATE(),@FECHA_INICIO,@FECHA_TERMINO,@PLAZO,@TIPO_EMPRESA,@ID_CCOSTO_UNEGOCIO,@ID_CLIENTE_SUCURSAL
,@STATUS_PROYECTO,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,@FECHA_PLAZO_NEG)




SET @ID_PROYECTO = SCOPE_IDENTITY();

INSERT INTO FACTURA (ID_PROYECTO,IDSEGMENTO) VALUES (@ID_PROYECTO,@IDSEGMENTOFACTURA)


IF(@HHSOCIOS>0)
BEGIN
DECLARE @COSTOUNITARIO DECIMAL(10,2)
SELECT @COSTOUNITARIO=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Socio'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio';
END;
IF(@HHSTAFF>0)
BEGIN
DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
        SELECT @ID_PROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
        FROM USUARIO U
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff';
END;
-- Para Consultores Externos
DECLARE @ConsultorA INT;
DECLARE @ConsultorB INT;
DECLARE @ConsultorC INT;

-- Asignar consultores A, B y C
SELECT 
    @ConsultorA = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'


SELECT 
    @ConsultorB = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'


SELECT 
    @ConsultorC = U.ID
FROM 
    USUARIO U
INNER JOIN 
    RECURSO R ON U.ID_RECURSO = R.ID
WHERE 
    R.NOMBRE_RECURSO = 'Consultor Externo' AND  R.TIPO_CONSULTOR = 'Consultor C'


-- Insertar horas para los consultores
IF (@HHCONSULTORA > 0 AND @ConsultorA IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORA = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE U.ID = @ConsultorA; -- Utilizar directamente el ID del usuario (consultor A)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORA, @IDSEGMENTOCONSULTORA);
END;

-- Para Consultor B
IF (@HHCONSULTORB > 0 AND @ConsultorB IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORB = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorB; -- Utilizar directamente el ID del usuario (consultor B)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORB, @IDSEGMENTOCONSULTORB);
END;

-- Para Consultor C
IF (@HHCONSULTORC > 0 AND @ConsultorC IS NOT NULL)
BEGIN
    DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
    SELECT @COSTOUNITARIOCONSULTORC = R.COSTO_UNITARIO
    FROM USUARIO U
	INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
    WHERE U.ID = @ConsultorC; -- Utilizar directamente el ID del usuario (consultor C)

    INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
    VALUES (@ID_PROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORC, @IDSEGMENTOCONSULTORC);
END;

DECLARE @IDPROYECTO_USUARIO INT;


INSERT INTO HH_USUARIO_HISTORIAL(ID_PROYECTO,HH_SOCIOS,HH_STAFF,HH_CONSULTORA,HH_CONSULTORB,HH_CONSULTORC) 

VALUES(@ID_PROYECTO,@HHSOCIOS,@HHSTAFF,@HHCONSULTORA,@HHCONSULTORB,@HHCONSULTORC)

IF(@STATUS_PROYECTO=1)
BEGIN
EXEC INSERTARNEGOCIACION @ID_PROYECTO,@AFECTAIVA,@MONTO,@PLAZO,@FECHA_INICIO,@FECHA_TERMINO,@FECHA_PLAZO_NEG,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,
@HHSOCIOS,@HHSTAFF,@HHCONSULTORA,@HHCONSULTORB,@HHCONSULTORC
END



END;


USE [PROYECTO_CONTROL_HORAS]
GO
/****** Object:  StoredProcedure [dbo].[EDITAR_PROYECTO]    Script Date: 15/10/2024 14:57:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[EDITAR_PROYECTO]
    @IDPROYECTO INT,
    @IDPRESUPUESTO INT,
    @MONTO DECIMAL(10,2),
    @MONEDA VARCHAR(200),
    @AFECTAIVA VARCHAR(10),
    @ID_TIPOLOGIA INT,
    @NOMBRE VARCHAR(MAX),
    @FECHA_INICIO DATE,
    @FECHA_TERMINO DATE,
    @PLAZO INT,
    @TIPO_EMPRESA INT,
    @ID_CCOSTO_UNEGOCIO INT,  
    @STATUS_PROYECTO INT,
    @PROBABILIDAD VARCHAR(200),
    @PORCENTAJE_PROBABILIDAD DECIMAL(10,2),
    @FECHA_PLAZO_NEG DATE,
    @HHSOCIOS INT,
    @HHSTAFF INT,
    @HHCONSULTORA INT,
    @HHCONSULTORB INT,
    @HHCONSULTORC INT,
    @IDSEGMENTOSOCIO INT,
    @IDSEGMENTOSTAFF INT,
    @IDSEGMENTOCONSULTORA INT,
    @IDSEGMENTOCONSULTORB INT,
    @IDSEGMENTOCONSULTORC INT,
    @IDSEGMENTOFACTURA INT
AS
BEGIN
    DECLARE @MONTOIVA DECIMAL(10,2) = 0;
    IF(@AFECTAIVA = 'si')
    BEGIN
        SET @MONTOIVA = @MONTO * 0.19;
    END;

    UPDATE PRESUPUESTO 
    SET MONTO = @MONTO, 
        MONEDA = @MONEDA, 
        AFECTAIVA = @AFECTAIVA, 
        MONTOIVA = @MONTOIVA 
    WHERE ID = @IDPRESUPUESTO;

    UPDATE PROYECTO 
    SET ID_PRESUPUESTO = @IDPRESUPUESTO,
        ID_TIPOLOGIA = @ID_TIPOLOGIA,
        NOMBRE = @NOMBRE,
        FECHA_INICIO = @FECHA_INICIO,
        FECHA_TERMINO = @FECHA_TERMINO,
        PLAZO = @PLAZO,
        TIPO_EMPRESA = @TIPO_EMPRESA,
        ID_CCOSTO_UNEGOCIO = @ID_CCOSTO_UNEGOCIO,
        STATUS_PROYECTO = @STATUS_PROYECTO,
        PROBABILIDAD = @PROBABILIDAD,
        PORCENTAJE_PROBABILIDAD = @PORCENTAJE_PROBABILIDAD,
        FECHA_PLAZO_NEG = @FECHA_PLAZO_NEG 
    WHERE ID = @IDPROYECTO;

    UPDATE FACTURA 
    SET IDSEGMENTO = @IDSEGMENTOFACTURA 
    WHERE ID_PROYECTO = @IDPROYECTO;

    DECLARE @ESTADO INT;
    SELECT @ESTADO = STATUS_PROYECTO FROM PROYECTO WHERE ID = @IDPROYECTO;



    -- Para Consultores Externos
    DECLARE @ConsultorA INT, @ConsultorB INT, @ConsultorC INT;

    -- Asignar consultores A, B y C
    SELECT @ConsultorA = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';

    SELECT @ConsultorB = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';

    SELECT @ConsultorC = U.ID
    FROM USUARIO U
    INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
    WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';

    -- Consultor A
    IF(@HHCONSULTORA <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
		DECLARE @CONSULTORAID INT;
			SELECT @CONSULTORAID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A' AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOCONSULTORA DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORA = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A';
        END;
		IF(@CONSULTORAID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORAA DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORAA = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorA;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORA, COSTOCONSULTORA, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorA, @HHCONSULTORA, @COSTOUNITARIOCONSULTORAA, @IDSEGMENTOCONSULTORA);
			
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORA = @HHCONSULTORA,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORA ELSE UP.COSTOCONSULTORA END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORA
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor A'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORA=@HHCONSULTORA WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor B
    IF(@HHCONSULTORB <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		 UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORBID INT;
			SELECT @CONSULTORBID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORB DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORB = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B';
        END;
		IF(@CONSULTORBID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORBB DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORBB = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorB;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORB, COSTOCONSULTORB, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorB, @HHCONSULTORB, @COSTOUNITARIOCONSULTORBB, @IDSEGMENTOCONSULTORB);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORB = @HHCONSULTORB,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORB ELSE UP.COSTOCONSULTORB END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORB
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor B'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORB=@HHCONSULTORB WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;

    -- Consultor C
	
	
    IF(@HHCONSULTORC <= 0)
	
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @CONSULTORCID INT;
			SELECT @CONSULTORCID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C' AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIOCONSULTORC DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOCONSULTORC = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C';
        END;

		IF(@CONSULTORCID IS NULL)
		BEGIN
			 DECLARE @COSTOUNITARIOCONSULTORCC DECIMAL(10,2);
			SELECT @COSTOUNITARIOCONSULTORCC = R.COSTO_UNITARIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON R.ID = U.ID_RECURSO
			WHERE U.ID = @ConsultorC;

			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO, HH_CONSULTORC, COSTOCONSULTORC, IDSEGMENTO)
			VALUES (@IDPROYECTO, @ConsultorC, @HHCONSULTORC, @COSTOUNITARIOCONSULTORCC, @IDSEGMENTOCONSULTORC);
			UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_CONSULTORC = @HHCONSULTORC,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOCONSULTORC ELSE UP.COSTOCONSULTORC END,
            UP.IDSEGMENTO = @IDSEGMENTOCONSULTORC
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Consultor Externo' AND R.TIPO_CONSULTOR = 'Consultor C'
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_CONSULTORC=@HHCONSULTORC WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HH SOCIOS*/
   IF(@HHSOCIOS <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
			DECLARE @SOCIOID INT;
			SELECT @SOCIOID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Socio'  AND UP.ID_PROYECTO = @IDPROYECTO

        DECLARE @COSTOUNITARIO DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIO = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Socio' ;
        END;
		IF(@SOCIOID IS NULL)
		BEGIN
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_SOCIOS,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSOCIOS,@COSTOUNITARIO,@IDSEGMENTOSOCIO
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Socio';
			UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_SOCIOS = @HHSOCIOS,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIO ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSOCIO
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Socio' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_SOCIOS=@HHSOCIOS WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;


	/*HHSTAFF*/
	IF(@HHSTAFF <= 0)
    BEGIN
        DELETE UP
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
    END
    ELSE
    BEGIN
		DECLARE @STAFFID INT;
			SELECT @STAFFID=ID_USUARIO FROM USUARIO_PROYECTO UP  
			INNER JOIN USUARIO U ON U.ID = UP.ID_USUARIO
			INNER JOIN RECURSO R ON R.ID=U.ID_RECURSO
			WHERE R.NOMBRE_RECURSO = 'Staff'  AND UP.ID_PROYECTO = @IDPROYECTO
        DECLARE @COSTOUNITARIOS DECIMAL(10,2);
        IF(@ESTADO = 1 OR @ESTADO = 5)
        BEGIN
            SELECT @COSTOUNITARIOS = COSTO_UNITARIO
            FROM RECURSO R
            WHERE R.NOMBRE_RECURSO = 'Staff' ;
        END;
		IF(@STAFFID IS NULL)
		BEGIN
			DECLARE @COSTOUNITARIOstaff DECIMAL(10,2)
			SELECT @COSTOUNITARIOstaff=COSTO_UNITARIO FROM RECURSO WHERE NOMBRE_RECURSO = 'Staff'  
			INSERT INTO USUARIO_PROYECTO (ID_PROYECTO, ID_USUARIO,HH_STAFF,CostoUnitarioAsignado,IDSEGMENTO)
			SELECT @IDPROYECTO, U.ID,@HHSTAFF,@COSTOUNITARIOstaff,@IDSEGMENTOSTAFF
			FROM USUARIO U
			INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
			WHERE R.NOMBRE_RECURSO = 'Staff';
			UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
		ELSE
		BEGIN
        UPDATE UP
        SET UP.HH_STAFF = @HHSTAFF,
            UP.CostoUnitarioAsignado = CASE WHEN @ESTADO = 1 OR @ESTADO = 5 THEN @COSTOUNITARIOS ELSE UP.CostoUnitarioAsignado END,
            UP.IDSEGMENTO = @IDSEGMENTOSTAFF
        FROM USUARIO_PROYECTO UP
        INNER JOIN USUARIO U ON UP.ID_USUARIO = U.ID
        INNER JOIN RECURSO R ON U.ID_RECURSO = R.ID
        WHERE R.NOMBRE_RECURSO = 'Staff' 
          AND UP.ID_PROYECTO = @IDPROYECTO;
		  UPDATE HH_USUARIO_HISTORIAL SET HH_STAFF=@HHSTAFF WHERE ID_PROYECTO=@IDPROYECTO
		END;
    END;
	IF(@STATUS_PROYECTO=1)
	BEGIN
	EXEC INSERTARNEGOCIACION @IDPROYECTO,@AFECTAIVA,@MONTO,@PLAZO,@FECHA_INICIO,@FECHA_TERMINO,@FECHA_PLAZO_NEG,@PROBABILIDAD,@PORCENTAJE_PROBABILIDAD,
@HHSOCIOS,@HHSTAFF,@HHCONSULTORA,@HHCONSULTORB,@HHCONSULTORC
	END;
END;
